/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pycava_bridge */

#ifndef _Included_pycava_bridge
#define _Included_pycava_bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pycava_bridge
 * Method:    Log
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pycava_bridge_Log
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pycava_bridge
 * Method:    Hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pycava_bridge_Hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
