/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pycava_bridge */

#ifndef _Included_pycava_bridge
#define _Included_pycava_bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pycava_bridge
 * Method:    Log
 * Signature: ([BS[IJFDCZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pycava_bridge_Log
  (JNIEnv *, jclass, jbyteArray, jshort, jintArray, jlong, jfloat, jdouble, jchar, jboolean, jstring);

/*
 * Class:     pycava_bridge
 * Method:    Hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pycava_bridge_Hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
